# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'inttttttt.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1406, 715)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.leftMenu = QtWidgets.QFrame(self.centralwidget)
        self.leftMenu.setGeometry(QtCore.QRect(0, 0, 200, 711))
        self.leftMenu.setMinimumSize(QtCore.QSize(43, 0))
        self.leftMenu.setMaximumSize(QtCore.QSize(200, 16777215))
        self.leftMenu.setStyleSheet("background-color:  #50507a;")
        self.leftMenu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.leftMenu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.leftMenu.setObjectName("leftMenu")
        self.aframe = QtWidgets.QFrame(self.leftMenu)
        self.aframe.setGeometry(QtCore.QRect(9, 9, 200, 344))
        self.aframe.setMinimumSize(QtCore.QSize(200, 225))
        self.aframe.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.aframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.aframe.setObjectName("aframe")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.aframe)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.aframe)
        self.pushButton_6.setMinimumSize(QtCore.QSize(200, 45))
        self.pushButton_6.setMaximumSize(QtCore.QSize(200, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton {\n"
"      background-color: #50507a;\n"
"    color: rgb(154, 154, 149);\n"
"    border: none;\n"
"    border-left: 3px solid rgb(25, 25, 25);\n"
"    text-align: left;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:  #ffffff;\n"
"    border-left: 3px solid rgb(46, 46, 184);\n"
"    background-color: rgb(18, 18, 18);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  #52527a;\n"
"}\n"
"\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../employee/minilogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_6.setIcon(icon)
        self.pushButton_6.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_4.addWidget(self.pushButton_6)
        self.pushButton_8 = QtWidgets.QPushButton(self.aframe)
        self.pushButton_8.setMinimumSize(QtCore.QSize(200, 45))
        self.pushButton_8.setMaximumSize(QtCore.QSize(200, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton {\n"
"      background-color: #50507a;\n"
"    color: rgb(154, 154, 149);\n"
"    border: none;\n"
"    border-left: 3px solid rgb(25, 25, 25);\n"
"    text-align: left;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:  #ffffff;\n"
"    border-left: 3px solid rgb(46, 46, 184);\n"
"    background-color: rgb(18, 18, 18);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  #52527a;\n"
"}\n"
"\n"
"")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../HRMA/HRMS/assets/account_box.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_4.addWidget(self.pushButton_8)
        self.pushButton_9 = QtWidgets.QPushButton(self.aframe)
        self.pushButton_9.setMinimumSize(QtCore.QSize(200, 45))
        self.pushButton_9.setMaximumSize(QtCore.QSize(200, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton {\n"
"      background-color: #50507a;\n"
"    color: rgb(154, 154, 149);\n"
"    border: none;\n"
"    border-left: 3px solid rgb(25, 25, 25);\n"
"    text-align: left;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:  #ffffff;\n"
"    border-left: 3px solid rgb(46, 46, 184);\n"
"    background-color: rgb(18, 18, 18);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  #52527a;\n"
"}\n"
"\n"
"")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../HRMA/HRMS/assets/screenshot.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon2)
        self.pushButton_9.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_4.addWidget(self.pushButton_9)
        self.pushButton_7 = QtWidgets.QPushButton(self.aframe)
        self.pushButton_7.setMinimumSize(QtCore.QSize(200, 45))
        self.pushButton_7.setMaximumSize(QtCore.QSize(200, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton {\n"
"      background-color: #50507a;\n"
"    color: rgb(154, 154, 149);\n"
"    border: none;\n"
"    border-left: 3px solid rgb(25, 25, 25);\n"
"    text-align: left;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:  #ffffff;\n"
"    border-left: 3px solid rgb(46, 46, 184);\n"
"    background-color: rgb(18, 18, 18);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  #52527a;\n"
"}\n"
"\n"
"")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../HRMA/HRMS/assets/teams.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_7.setIcon(icon3)
        self.pushButton_7.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_7.setObjectName("pushButton_7")
        self.verticalLayout_4.addWidget(self.pushButton_7)
        self.pushButton_5 = QtWidgets.QPushButton(self.aframe)
        self.pushButton_5.setMinimumSize(QtCore.QSize(200, 45))
        self.pushButton_5.setMaximumSize(QtCore.QSize(200, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton {\n"
"      background-color: #50507a;\n"
"    color: rgb(154, 154, 149);\n"
"    border: none;\n"
"    border-left: 3px solid rgb(25, 25, 25);\n"
"    text-align: left;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:  #ffffff;\n"
"    border-left: 3px solid rgb(46, 46, 184);\n"
"    background-color: rgb(18, 18, 18);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  #52527a;\n"
"}\n"
"\n"
"")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../HRMA/HRMS/assets/timetrack.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_5.setIcon(icon4)
        self.pushButton_5.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5)
        self.pushButton_3 = QtWidgets.QPushButton(self.aframe)
        self.pushButton_3.setMinimumSize(QtCore.QSize(200, 45))
        self.pushButton_3.setMaximumSize(QtCore.QSize(200, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton {\n"
"      background-color: #50507a;\n"
"    color: rgb(154, 154, 149);\n"
"    border: none;\n"
"    border-left: 3px solid rgb(25, 25, 25);\n"
"    text-align: left;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:  #ffffff;\n"
"    border-left: 3px solid rgb(46, 46, 184);\n"
"    background-color: rgb(18, 18, 18);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  #52527a;\n"
"}\n"
"\n"
"")
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.aframe)
        self.pushButton_4.setMinimumSize(QtCore.QSize(200, 45))
        self.pushButton_4.setMaximumSize(QtCore.QSize(200, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"      background-color: #50507a;\n"
"    color: rgb(154, 154, 149);\n"
"    border: none;\n"
"    border-left: 3px solid rgb(25, 25, 25);\n"
"    text-align: left;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:  #ffffff;\n"
"    border-left: 3px solid rgb(46, 46, 184);\n"
"    background-color: rgb(18, 18, 18);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  #52527a;\n"
"}\n"
"\n"
"")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../HRMA/HRMS/assets/chat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon5)
        self.pushButton_4.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_4.addWidget(self.pushButton_4)
        self.pushButton_2 = QtWidgets.QPushButton(self.aframe)
        self.pushButton_2.setMinimumSize(QtCore.QSize(200, 45))
        self.pushButton_2.setMaximumSize(QtCore.QSize(200, 45))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("QPushButton {\n"
"      background-color: #50507a;\n"
"    color: rgb(154, 154, 149);\n"
"    border: none;\n"
"    border-left: 3px solid rgb(25, 25, 25);\n"
"    text-align: left;\n"
"    padding-left: 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color:  #ffffff;\n"
"    border-left: 3px solid rgb(46, 46, 184);\n"
"    background-color: rgb(18, 18, 18);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color:  #52527a;\n"
"}\n"
"\n"
"")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../HRMA/HRMS/assets/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon6)
        self.pushButton_2.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(200, 50, 350, 281))
        self.frame_4.setMinimumSize(QtCore.QSize(350, 0))
        self.frame_4.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_4.setStyleSheet("background-color:#003366;")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_10 = QtWidgets.QFrame(self.frame_4)
        self.frame_10.setStyleSheet("QFrame {\n"
"    background-color: rgb(25, 25, 25);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"\n"
"    border: 1px solid rgb(255, 85, 0);\n"
"}")
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_9.setContentsMargins(0, 20, 0, 20)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("QLabel {\n"
"    color: rgb(152, 152, 152);\n"
"    border: none;\n"
"}")
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_9.addWidget(self.label_11)
        self.label_10 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("QLabel {\n"
"    color: rgb(199, 199, 199);\n"
"    border: none;\n"
"}")
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_9.addWidget(self.label_10)
        self.label_13 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("QLabel {\n"
"    color: #ffffff;\n"
"    border: none;\n"
"}")
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_9.addWidget(self.label_13)
        self.label_12 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel {\n"
"    color: rgb(153, 153, 153);\n"
"    border: none;\n"
"}\n"
"")
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_9.addWidget(self.label_12)
        self.gridLayout.addWidget(self.frame_10, 1, 0, 1, 1)
        self.frame_9 = QtWidgets.QFrame(self.frame_4)
        self.frame_9.setStyleSheet("QFrame {\n"
"    background-color: rgb(25, 25, 25);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"   \n"
"    border: 1px solid rgb(255, 85, 0);\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_8.setContentsMargins(0, 20, 0, 20)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("QLabel {\n"
"    color: rgb(152, 152, 152);\n"
"    border: none;\n"
"}")
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_8.addWidget(self.label_7)
        self.label_6 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel {\n"
"    color: rgb(199, 199, 199);\n"
"    border: none;\n"
"}")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.label_9 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel {\n"
"    color: #ffffff;\n"
"    border: none;\n"
"}")
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_8.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel {\n"
"    color: rgb(153, 153, 153);\n"
"    border: none;\n"
"}\n"
"")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_8.addWidget(self.label_8)
        self.gridLayout.addWidget(self.frame_9, 0, 1, 1, 1)
        self.frame_11 = QtWidgets.QFrame(self.frame_4)
        self.frame_11.setStyleSheet("QFrame {\n"
"    background-color: rgb(25, 25, 25);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    \n"
"    border: 1px solid rgb(255, 85, 0);\n"
"}")
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_10.setContentsMargins(0, 20, 0, 20)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_15 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("QLabel {\n"
"    color: rgb(152, 152, 152);\n"
"    border: none;\n"
"}")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_10.addWidget(self.label_15)
        self.label_14 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("QLabel {\n"
"    color: rgb(199, 199, 199);\n"
"    border: none;\n"
"}")
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_10.addWidget(self.label_14)
        self.label_17 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("QLabel {\n"
"    color: #ffffff;\n"
"    border: none;\n"
"}")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_10.addWidget(self.label_17)
        self.label_16 = QtWidgets.QLabel(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("QLabel {\n"
"    color: rgb(153, 153, 153);\n"
"    border: none;\n"
"}\n"
"")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_10.addWidget(self.label_16)
        self.gridLayout.addWidget(self.frame_11, 1, 1, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setStyleSheet("QFrame {\n"
"    background-color: rgb(25, 25, 25);\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    \n"
"    border: 1px solid rgb(255, 85, 0);\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_7.setContentsMargins(0, 20, 0, 20)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel {\n"
"    color: rgb(152, 152, 152);\n"
"    border: none;\n"
"}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_7.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel {\n"
"    color: rgb(199, 199, 199);\n"
"    border: none;\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.gridLayout.addWidget(self.frame_8, 0, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(200, 0, 250, 51))
        self.frame_6.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_6.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_6.setStyleSheet("background-color: rgb(13, 9, 36);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit.setGeometry(QtCore.QRect(50, 10, 191, 41))
        self.lineEdit.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit.setStyleSheet("background-color:#ffffff;\n"
" border: 1px solid #ccc;  \n"
"border-radius: 15px;\n"
"\n"
"input[type=text] {\n"
"    border: 1px solid #ccc;  \n"
"  }")
        self.lineEdit.setObjectName("lineEdit")
        self.label_4 = QtWidgets.QLabel(self.frame_6)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.label_4.setStyleSheet("")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../../Downloads/search-3-xxl (1) (1).png"))
        self.label_4.setObjectName("label_4")
        self.ProjectFrame = QtWidgets.QFrame(self.centralwidget)
        self.ProjectFrame.setGeometry(QtCore.QRect(198, 328, 861, 431))
        self.ProjectFrame.setStyleSheet("QFrame {\n"
"    background-color: #50507a;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"}\n"
"")
        self.ProjectFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ProjectFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ProjectFrame.setObjectName("ProjectFrame")
        self.label_18 = QtWidgets.QLabel(self.ProjectFrame)
        self.label_18.setGeometry(QtCore.QRect(20, 20, 150, 31))
        self.label_18.setMinimumSize(QtCore.QSize(150, 0))
        self.label_18.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_18.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_18.setObjectName("label_18")
        self.frame_12 = QtWidgets.QFrame(self.ProjectFrame)
        self.frame_12.setGeometry(QtCore.QRect(10, 50, 511, 361))
        self.frame_12.setStyleSheet("background-color:#003366;\n"
"")
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.label_19 = QtWidgets.QLabel(self.frame_12)
        self.label_19.setGeometry(QtCore.QRect(80, 10, 58, 23))
        self.label_19.setObjectName("label_19")
        self.label_35 = QtWidgets.QLabel(self.frame_12)
        self.label_35.setGeometry(QtCore.QRect(150, 10, 61, 20))
        self.label_35.setMinimumSize(QtCore.QSize(0, 20))
        self.label_35.setMaximumSize(QtCore.QSize(70, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: rgb(203, 203, 203);\n"
"background-color: rgb(255, 17, 80);\n"
"padding: 1px;\n"
"border-radius: 8px;")
        self.label_35.setObjectName("label_35")
        self.frame_3 = QtWidgets.QFrame(self.frame_12)
        self.frame_3.setGeometry(QtCore.QRect(230, 0, 281, 361))
        self.frame_3.setStyleSheet("background-color:#660066;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.toggleButton_7 = QtWidgets.QPushButton(self.frame_3)
        self.toggleButton_7.setGeometry(QtCore.QRect(120, 20, 90, 26))
        self.toggleButton_7.setMinimumSize(QtCore.QSize(90, 26))
        self.toggleButton_7.setMaximumSize(QtCore.QSize(90, 26))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.toggleButton_7.setFont(font)
        self.toggleButton_7.setStyleSheet("QPushButton {\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    background-color: rgb(30, 30, 30);\n"
"    border-left: 3px solid rgb(30, 30, 30);\n"
"    border-right: 3px solid rgb(30, 30, 30);\n"
"    color:#ffffff;\n"
"    border-radius: 13px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-left: 3px solid rgb(255, 85, 0);\n"
"    border-right: 3px solid rgb(255, 85, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(25, 25, 25);\n"
"}")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../../../Downloads/25-254406_white-person-icon-png-people-white-icon-png (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toggleButton_7.setIcon(icon7)
        self.toggleButton_7.setObjectName("toggleButton_7")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_10.setGeometry(QtCore.QRect(0, 10, 36, 36))
        self.pushButton_10.setMinimumSize(QtCore.QSize(36, 36))
        self.pushButton_10.setMaximumSize(QtCore.QSize(36, 36))
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgb(13, 9, 36);\n"
"    border-radius: 18;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 0, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.pushButton_10.setText("")
        self.pushButton_10.setIcon(icon7)
        self.pushButton_10.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_20 = QtWidgets.QLabel(self.frame_3)
        self.label_20.setGeometry(QtCore.QRect(40, 0, 91, 61))
        self.label_20.setStyleSheet("")
        self.label_20.setObjectName("label_20")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setGeometry(QtCore.QRect(20, 100, 261, 241))
        self.frame_2.setStyleSheet("background-color:#ffffff;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_11.setGeometry(QtCore.QRect(0, 0, 261, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setStyleSheet("\n"
".QPushButton:hover {\n"
"  background-color: #993399;\n"
"}\n"
"\n"
".QPushButton{\n"
" background-color: #52527a;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"}")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../../../Downloads/png-transparent-businessperson-computer-icons-avatar-avatar-heroes-public-relations-business (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon8)
        self.pushButton_11.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_12.setGeometry(QtCore.QRect(0, 80, 261, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setStyleSheet("\n"
".QPushButton:hover {\n"
"  background-color: #993399;\n"
"}\n"
"\n"
".QPushButton{\n"
" background-color: #52527a;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"}")
        self.pushButton_12.setIcon(icon8)
        self.pushButton_12.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_13.setGeometry(QtCore.QRect(0, 160, 261, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        self.pushButton_13.setStyleSheet("\n"
".QPushButton:hover {\n"
"  background-color: #993399;\n"
"}\n"
"\n"
".QPushButton{\n"
" background-color: #52527a;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"}")
        self.pushButton_13.setIcon(icon8)
        self.pushButton_13.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_13.setObjectName("pushButton_13")
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setGeometry(QtCore.QRect(30, 60, 250, 41))
        self.frame_7.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_7.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_7.setStyleSheet("background-color: rgb(13, 9, 36);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 10, 201, 41))
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_2.setStyleSheet("background-color:#ffffff;\n"
" border: 1px solid #ccc;  \n"
"\n"
"input[type=text] {\n"
"    border: 1px solid #ccc;  \n"
"  }")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../../../Downloads/search-3-xxl (1) (1).png"))
        self.label_5.setObjectName("label_5")
        self.frame_45 = QtWidgets.QFrame(self.frame_12)
        self.frame_45.setGeometry(QtCore.QRect(20, 200, 211, 151))
        self.frame_45.setStyleSheet("border: 1px solid rgb(34, 24, 97);\n"
" background-color: #52527a;")
        self.frame_45.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.label_21 = QtWidgets.QLabel(self.frame_45)
        self.label_21.setGeometry(QtCore.QRect(20, 20, 38, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("QLabel {\n"
"    color: rgb(152, 152, 152);\n"
"    border: none;\n"
"}")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.frame_5 = QtWidgets.QFrame(self.frame_45)
        self.frame_5.setGeometry(QtCore.QRect(80, 10, 131, 141))
        self.frame_5.setStyleSheet("background-color:#003366;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_22 = QtWidgets.QLabel(self.frame_5)
        self.label_22.setGeometry(QtCore.QRect(30, 10, 69, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("QLabel {\n"
"    color: rgb(152, 152, 152);\n"
"    border: none;\n"
"}")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_24 = QtWidgets.QLabel(self.frame_5)
        self.label_24.setGeometry(QtCore.QRect(30, 50, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("QLabel {\n"
"    color: rgb(199, 199, 199);\n"
"    border: none;\n"
"}")
        self.label_24.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_24.setObjectName("label_24")
        self.label_23 = QtWidgets.QLabel(self.frame_45)
        self.label_23.setGeometry(QtCore.QRect(10, 60, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("QLabel {\n"
"    color: rgb(199, 199, 199);\n"
"    border: none;\n"
"}")
        self.label_23.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_23.setObjectName("label_23")
        self.label = QtWidgets.QLabel(self.frame_12)
        self.label.setGeometry(QtCore.QRect(10, 0, 71, 61))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../employee/minilogo.png"))
        self.label.setObjectName("label")
        self.frame_46 = QtWidgets.QFrame(self.frame_12)
        self.frame_46.setGeometry(QtCore.QRect(20, 60, 211, 131))
        self.frame_46.setStyleSheet("border: 1px solid rgb(34, 24, 97);\n"
" background-color: #52527a;")
        self.frame_46.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.frame_13 = QtWidgets.QFrame(self.frame_46)
        self.frame_13.setGeometry(QtCore.QRect(0, 70, 211, 81))
        self.frame_13.setStyleSheet("background-color:#003366;")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_25 = QtWidgets.QLabel(self.frame_13)
        self.label_25.setGeometry(QtCore.QRect(10, 10, 81, 23))
        self.label_25.setObjectName("label_25")
        self.progressBar_5 = QtWidgets.QProgressBar(self.frame_13)
        self.progressBar_5.setGeometry(QtCore.QRect(10, 40, 169, 16))
        self.progressBar_5.setMinimumSize(QtCore.QSize(0, 16))
        self.progressBar_5.setMaximumSize(QtCore.QSize(16777215, 16))
        self.progressBar_5.setStyleSheet("QProgressBar {\n"
"    color: rgb(177, 177, 177);\n"
"    border: none;\n"
"    background-color: rgb(102, 102, 102);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #ff0000;\n"
"    border-radius : 8px;\n"
"}     ")
        self.progressBar_5.setProperty("value", 79)
        self.progressBar_5.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_5.setTextVisible(False)
        self.progressBar_5.setObjectName("progressBar_5")
        self.label_62 = QtWidgets.QLabel(self.frame_13)
        self.label_62.setGeometry(QtCore.QRect(120, 10, 61, 20))
        self.label_62.setMinimumSize(QtCore.QSize(0, 20))
        self.label_62.setMaximumSize(QtCore.QSize(70, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setStyleSheet("color: rgb(203, 203, 203);\n"
"background-color: rgb(255, 17, 80);\n"
"padding: 1px;\n"
"border-radius: 8px;")
        self.label_62.setObjectName("label_62")
        self.label_26 = QtWidgets.QLabel(self.frame_46)
        self.label_26.setGeometry(QtCore.QRect(10, 20, 81, 23))
        self.label_26.setObjectName("label_26")
        self.label_63 = QtWidgets.QLabel(self.frame_46)
        self.label_63.setGeometry(QtCore.QRect(130, 20, 47, 20))
        self.label_63.setMinimumSize(QtCore.QSize(0, 20))
        self.label_63.setMaximumSize(QtCore.QSize(70, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setStyleSheet("color:#ffffff;\n"
"background-color: rgb(255, 17, 80);\n"
"padding: 1px;\n"
"border-radius: 8px;")
        self.label_63.setObjectName("label_63")
        self.progressBar_4 = QtWidgets.QProgressBar(self.frame_46)
        self.progressBar_4.setGeometry(QtCore.QRect(10, 50, 171, 16))
        self.progressBar_4.setMinimumSize(QtCore.QSize(0, 16))
        self.progressBar_4.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.progressBar_4.setFont(font)
        self.progressBar_4.setAutoFillBackground(False)
        self.progressBar_4.setStyleSheet("QProgressBar {\n"
"    color: rgb(177, 177, 177);\n"
"    border: none;\n"
"    background-color: rgb(102, 102, 102);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(7, 255, 119);\n"
"    border-radius : 8px;\n"
"}     ")
        self.progressBar_4.setProperty("value", 75)
        self.progressBar_4.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_4.setTextVisible(False)
        self.progressBar_4.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_4.setInvertedAppearance(False)
        self.progressBar_4.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_4.setObjectName("progressBar_4")
        self.listView = QtWidgets.QListView(self.ProjectFrame)
        self.listView.setGeometry(QtCore.QRect(540, 10, 291, 381))
        self.listView.setStyleSheet(" background-color: #993399;\n"
"")
        self.listView.setObjectName("listView")
        self.frame = QtWidgets.QFrame(self.ProjectFrame)
        self.frame.setGeometry(QtCore.QRect(540, 40, 151, 41))
        self.frame.setStyleSheet(" background-color: #993399;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame)
        self.pushButton_14.setGeometry(QtCore.QRect(10, 0, 36, 36))
        self.pushButton_14.setMinimumSize(QtCore.QSize(36, 36))
        self.pushButton_14.setMaximumSize(QtCore.QSize(36, 36))
        self.pushButton_14.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgb(13, 9, 36);\n"
"    border-radius: 18;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 0, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.pushButton_14.setText("")
        self.pushButton_14.setIcon(icon7)
        self.pushButton_14.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_27 = QtWidgets.QLabel(self.frame)
        self.label_27.setGeometry(QtCore.QRect(50, 0, 101, 31))
        self.label_27.setStyleSheet("")
        self.label_27.setObjectName("label_27")
        self.pushButton_15 = QtWidgets.QPushButton(self.ProjectFrame)
        self.pushButton_15.setGeometry(QtCore.QRect(530, 80, 291, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setStyleSheet("\n"
".QPushButton:hover {\n"
"  background-color: #52527a;\n"
"}\n"
"\n"
".QPushButton{\n"
"background-color:#003366;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"}")
        self.pushButton_15.setIcon(icon8)
        self.pushButton_15.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.ProjectFrame)
        self.pushButton_16.setGeometry(QtCore.QRect(530, 110, 291, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        self.pushButton_16.setStyleSheet("\n"
".QPushButton:hover {\n"
"  background-color: #52527a;\n"
"}\n"
"\n"
".QPushButton{\n"
"background-color:#003366;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"}")
        self.pushButton_16.setIcon(icon8)
        self.pushButton_16.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.ProjectFrame)
        self.pushButton_17.setGeometry(QtCore.QRect(530, 140, 291, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setStyleSheet("\n"
".QPushButton:hover {\n"
"  background-color: #52527a;\n"
"}\n"
"\n"
".QPushButton{\n"
"background-color:#003366;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"}")
        self.pushButton_17.setIcon(icon8)
        self.pushButton_17.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.ProjectFrame)
        self.pushButton_18.setGeometry(QtCore.QRect(530, 170, 291, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_18.sizePolicy().hasHeightForWidth())
        self.pushButton_18.setSizePolicy(sizePolicy)
        self.pushButton_18.setStyleSheet("\n"
".QPushButton:hover {\n"
"  background-color: #52527a;\n"
"}\n"
"\n"
".QPushButton{\n"
"background-color:#003366;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"}")
        self.pushButton_18.setIcon(icon8)
        self.pushButton_18.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.ProjectFrame)
        self.pushButton_19.setGeometry(QtCore.QRect(530, 200, 291, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_19.sizePolicy().hasHeightForWidth())
        self.pushButton_19.setSizePolicy(sizePolicy)
        self.pushButton_19.setStyleSheet("\n"
".QPushButton:hover {\n"
"  background-color: #52527a;\n"
"}\n"
"\n"
".QPushButton{\n"
"background-color:#003366;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"}")
        self.pushButton_19.setIcon(icon8)
        self.pushButton_19.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.ProjectFrame)
        self.pushButton_20.setGeometry(QtCore.QRect(530, 230, 291, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_20.sizePolicy().hasHeightForWidth())
        self.pushButton_20.setSizePolicy(sizePolicy)
        self.pushButton_20.setStyleSheet("\n"
".QPushButton:hover {\n"
"  background-color: #52527a;\n"
"}\n"
"\n"
".QPushButton{\n"
"background-color:#003366;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"}")
        self.pushButton_20.setIcon(icon8)
        self.pushButton_20.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.ProjectFrame)
        self.pushButton_21.setGeometry(QtCore.QRect(530, 260, 291, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_21.sizePolicy().hasHeightForWidth())
        self.pushButton_21.setSizePolicy(sizePolicy)
        self.pushButton_21.setStyleSheet("\n"
".QPushButton:hover {\n"
"  background-color: #52527a;\n"
"}\n"
"\n"
".QPushButton{\n"
"background-color:#003366;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"}")
        self.pushButton_21.setIcon(icon8)
        self.pushButton_21.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_21.setObjectName("pushButton_21")
        self.label_36 = QtWidgets.QLabel(self.ProjectFrame)
        self.label_36.setGeometry(QtCore.QRect(760, 80, 61, 20))
        self.label_36.setMinimumSize(QtCore.QSize(0, 20))
        self.label_36.setMaximumSize(QtCore.QSize(70, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("color: rgb(203, 203, 203);\n"
"background-color: rgb(255, 17, 80);\n"
"padding: 1px;\n"
"border-radius: 8px;")
        self.label_36.setObjectName("label_36")
        self.label_37 = QtWidgets.QLabel(self.ProjectFrame)
        self.label_37.setGeometry(QtCore.QRect(760, 110, 61, 20))
        self.label_37.setMinimumSize(QtCore.QSize(0, 20))
        self.label_37.setMaximumSize(QtCore.QSize(70, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("color: rgb(203, 203, 203);\n"
"background-color: rgb(255, 17, 80);\n"
"padding: 1px;\n"
"border-radius: 8px;")
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.ProjectFrame)
        self.label_38.setGeometry(QtCore.QRect(760, 140, 61, 20))
        self.label_38.setMinimumSize(QtCore.QSize(0, 20))
        self.label_38.setMaximumSize(QtCore.QSize(70, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("color: rgb(203, 203, 203);\n"
"background-color: rgb(255, 17, 80);\n"
"padding: 1px;\n"
"border-radius: 8px;")
        self.label_38.setObjectName("label_38")
        self.label_64 = QtWidgets.QLabel(self.ProjectFrame)
        self.label_64.setGeometry(QtCore.QRect(770, 170, 47, 20))
        self.label_64.setMinimumSize(QtCore.QSize(0, 20))
        self.label_64.setMaximumSize(QtCore.QSize(70, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_64.setFont(font)
        self.label_64.setStyleSheet("color:#ffffff;\n"
"background-color:  rgb(7, 255, 119);\n"
"padding: 1px;\n"
"border-radius: 8px;")
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.ProjectFrame)
        self.label_65.setGeometry(QtCore.QRect(760, 200, 61, 20))
        self.label_65.setMinimumSize(QtCore.QSize(0, 20))
        self.label_65.setMaximumSize(QtCore.QSize(70, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_65.setFont(font)
        self.label_65.setStyleSheet("color:#ffffff;\n"
"background-color:  rgb(7, 255, 119);\n"
"padding: 1px;\n"
"border-radius: 8px;")
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.ProjectFrame)
        self.label_66.setGeometry(QtCore.QRect(760, 230, 61, 20))
        self.label_66.setMinimumSize(QtCore.QSize(0, 20))
        self.label_66.setMaximumSize(QtCore.QSize(70, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_66.setFont(font)
        self.label_66.setStyleSheet("color:#ffffff;\n"
"background-color:  rgb(7, 255, 119);\n"
"padding: 1px;\n"
"border-radius: 8px;")
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.ProjectFrame)
        self.label_67.setGeometry(QtCore.QRect(760, 260, 61, 20))
        self.label_67.setMinimumSize(QtCore.QSize(0, 20))
        self.label_67.setMaximumSize(QtCore.QSize(70, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_67.setFont(font)
        self.label_67.setStyleSheet("color:#ffffff;\n"
"background-color:  rgb(7, 255, 119);\n"
"padding: 1px;\n"
"border-radius: 8px;")
        self.label_67.setObjectName("label_67")
        self.pushButton_22 = QtWidgets.QPushButton(self.ProjectFrame)
        self.pushButton_22.setGeometry(QtCore.QRect(530, 290, 291, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_22.sizePolicy().hasHeightForWidth())
        self.pushButton_22.setSizePolicy(sizePolicy)
        self.pushButton_22.setStyleSheet("\n"
".QPushButton:hover {\n"
"  background-color: #52527a;\n"
"}\n"
"\n"
".QPushButton{\n"
"background-color:#003366;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"}")
        self.pushButton_22.setIcon(icon8)
        self.pushButton_22.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_48 = QtWidgets.QPushButton(self.ProjectFrame)
        self.pushButton_48.setGeometry(QtCore.QRect(530, 320, 291, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_48.sizePolicy().hasHeightForWidth())
        self.pushButton_48.setSizePolicy(sizePolicy)
        self.pushButton_48.setStyleSheet("\n"
".QPushButton:hover {\n"
"  background-color: #52527a;\n"
"}\n"
"\n"
".QPushButton{\n"
"background-color:#003366;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"}")
        self.pushButton_48.setIcon(icon8)
        self.pushButton_48.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_48.setObjectName("pushButton_48")
        self.pushButton_49 = QtWidgets.QPushButton(self.ProjectFrame)
        self.pushButton_49.setGeometry(QtCore.QRect(530, 350, 291, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_49.sizePolicy().hasHeightForWidth())
        self.pushButton_49.setSizePolicy(sizePolicy)
        self.pushButton_49.setStyleSheet("\n"
".QPushButton:hover {\n"
"  background-color: #52527a;\n"
"}\n"
"\n"
".QPushButton{\n"
"background-color:#003366;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"}")
        self.pushButton_49.setIcon(icon8)
        self.pushButton_49.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_49.setObjectName("pushButton_49")
        self.comboBox = QtWidgets.QComboBox(self.ProjectFrame)
        self.comboBox.setGeometry(QtCore.QRect(160, 20, 194, 22))
        self.comboBox.setStyleSheet("\n"
"  background-color: #f9f9f9;\n"
"  min-width: 160px;\n"
"  box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.frame_14 = QtWidgets.QFrame(self.centralwidget)
        self.frame_14.setGeometry(QtCore.QRect(550, 50, 501, 281))
        self.frame_14.setStyleSheet("background-color:#50507a;")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.label_28 = QtWidgets.QLabel(self.frame_14)
        self.label_28.setGeometry(QtCore.QRect(10, 0, 131, 31))
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.frame_14)
        self.label_29.setGeometry(QtCore.QRect(0, 30, 511, 411))
        self.label_29.setText("")
        self.label_29.setPixmap(QtGui.QPixmap("SVG-UC-Bar.svg"))
        self.label_29.setObjectName("label_29")
        self.frame_15 = QtWidgets.QFrame(self.centralwidget)
        self.frame_15.setGeometry(QtCore.QRect(449, -1, 601, 51))
        self.frame_15.setStyleSheet("background-color:#32324d;")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_31 = QtWidgets.QLabel(self.frame_15)
        self.label_31.setGeometry(QtCore.QRect(300, 10, 31, 41))
        self.label_31.setStyleSheet("border: 0.3px ; border-radius: 25%; background-clip: padding;")
        self.label_31.setText("")
        self.label_31.setPixmap(QtGui.QPixmap("../../../Downloads/png-transparent-businessperson-computer-icons-avatar-avatar-heroes-public-relations-business (1).png"))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.frame_15)
        self.label_32.setGeometry(QtCore.QRect(340, 20, 191, 31))
        self.label_32.setObjectName("label_32")
        self.pushButton_47 = QtWidgets.QPushButton(self.frame_15)
        self.pushButton_47.setGeometry(QtCore.QRect(250, 10, 36, 36))
        self.pushButton_47.setMinimumSize(QtCore.QSize(36, 36))
        self.pushButton_47.setMaximumSize(QtCore.QSize(36, 36))
        self.pushButton_47.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgb(13, 9, 36);\n"
"    border-radius: 18;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 0, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.pushButton_47.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icons/icons/bell.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_47.setIcon(icon9)
        self.pushButton_47.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_47.setObjectName("pushButton_47")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(1046, -10, 361, 731))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setStyleSheet(" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(56, 56, 85);\n"
" }")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1218, 1218))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_16 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_16.setMinimumSize(QtCore.QSize(1200, 1200))
        self.frame_16.setStyleSheet("background-color:#660066;")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.pushButton = QtWidgets.QPushButton(self.frame_16)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 81, 31))
        self.pushButton.setStyleSheet("border-radius: 12px;\n"
"text-align: center;\n"
"color:#ffffff;\n"
"background-color:#cc33ff;")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("../../../Downloads/67-679828_white-plus-png-plus-icon-white-png-transparent (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon10)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_23 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_23.setGeometry(QtCore.QRect(0, 30, 331, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_23.sizePolicy().hasHeightForWidth())
        self.pushButton_23.setSizePolicy(sizePolicy)
        self.pushButton_23.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"")
        self.pushButton_23.setIcon(icon8)
        self.pushButton_23.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_24.setGeometry(QtCore.QRect(0, 90, 331, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_24.sizePolicy().hasHeightForWidth())
        self.pushButton_24.setSizePolicy(sizePolicy)
        self.pushButton_24.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"")
        self.pushButton_24.setIcon(icon8)
        self.pushButton_24.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_25.setGeometry(QtCore.QRect(0, 150, 331, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_25.sizePolicy().hasHeightForWidth())
        self.pushButton_25.setSizePolicy(sizePolicy)
        self.pushButton_25.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"")
        self.pushButton_25.setIcon(icon8)
        self.pushButton_25.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_26.setGeometry(QtCore.QRect(0, 210, 331, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_26.sizePolicy().hasHeightForWidth())
        self.pushButton_26.setSizePolicy(sizePolicy)
        self.pushButton_26.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"")
        self.pushButton_26.setIcon(icon8)
        self.pushButton_26.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_27.setGeometry(QtCore.QRect(0, 270, 331, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_27.sizePolicy().hasHeightForWidth())
        self.pushButton_27.setSizePolicy(sizePolicy)
        self.pushButton_27.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"")
        self.pushButton_27.setIcon(icon8)
        self.pushButton_27.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_28.setGeometry(QtCore.QRect(0, 330, 331, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_28.sizePolicy().hasHeightForWidth())
        self.pushButton_28.setSizePolicy(sizePolicy)
        self.pushButton_28.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"")
        self.pushButton_28.setIcon(icon8)
        self.pushButton_28.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_29.setGeometry(QtCore.QRect(0, 390, 331, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_29.sizePolicy().hasHeightForWidth())
        self.pushButton_29.setSizePolicy(sizePolicy)
        self.pushButton_29.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"")
        self.pushButton_29.setIcon(icon8)
        self.pushButton_29.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_30.setGeometry(QtCore.QRect(0, 450, 331, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_30.sizePolicy().hasHeightForWidth())
        self.pushButton_30.setSizePolicy(sizePolicy)
        self.pushButton_30.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"")
        self.pushButton_30.setIcon(icon8)
        self.pushButton_30.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_31.setGeometry(QtCore.QRect(0, 510, 331, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_31.sizePolicy().hasHeightForWidth())
        self.pushButton_31.setSizePolicy(sizePolicy)
        self.pushButton_31.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"")
        self.pushButton_31.setIcon(icon8)
        self.pushButton_31.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_32.setGeometry(QtCore.QRect(0, 570, 331, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_32.sizePolicy().hasHeightForWidth())
        self.pushButton_32.setSizePolicy(sizePolicy)
        self.pushButton_32.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"")
        self.pushButton_32.setIcon(icon8)
        self.pushButton_32.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_33 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_33.setGeometry(QtCore.QRect(0, 630, 331, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_33.sizePolicy().hasHeightForWidth())
        self.pushButton_33.setSizePolicy(sizePolicy)
        self.pushButton_33.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"")
        self.pushButton_33.setIcon(icon8)
        self.pushButton_33.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_34 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_34.setGeometry(QtCore.QRect(0, 690, 331, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_34.sizePolicy().hasHeightForWidth())
        self.pushButton_34.setSizePolicy(sizePolicy)
        self.pushButton_34.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"")
        self.pushButton_34.setIcon(icon8)
        self.pushButton_34.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_35 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_35.setGeometry(QtCore.QRect(240, 40, 71, 31))
        self.pushButton_35.setStyleSheet(" .QPushButton{\n"
"  background-color: DodgerBlue;\n"
"border-radius: 12px;\n"
"  color: white;\n"
"font: 75 7pt bold \"MS Shell Dlg 2\";\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: RoyalBlue;\n"
"}")
        self.pushButton_35.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_36 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_36.setGeometry(QtCore.QRect(240, 100, 71, 31))
        self.pushButton_36.setStyleSheet(" .QPushButton{\n"
"  background-color: DodgerBlue;\n"
"border-radius: 12px;\n"
"  color: white;\n"
"font: 75 7pt bold \"MS Shell Dlg 2\";\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: RoyalBlue;\n"
"}")
        self.pushButton_36.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_37 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_37.setGeometry(QtCore.QRect(240, 160, 71, 31))
        self.pushButton_37.setStyleSheet(" .QPushButton{\n"
"  background-color: DodgerBlue;\n"
"border-radius: 12px;\n"
"  color: white;\n"
"font: 75 7pt bold \"MS Shell Dlg 2\";\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: RoyalBlue;\n"
"}")
        self.pushButton_37.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_38 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_38.setGeometry(QtCore.QRect(240, 220, 71, 31))
        self.pushButton_38.setStyleSheet(" .QPushButton{\n"
"  background-color: DodgerBlue;\n"
"border-radius: 12px;\n"
"  color: white;\n"
"font: 75 7pt bold \"MS Shell Dlg 2\";\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: RoyalBlue;\n"
"}")
        self.pushButton_38.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_39 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_39.setGeometry(QtCore.QRect(240, 280, 71, 31))
        self.pushButton_39.setStyleSheet(" .QPushButton{\n"
"  background-color: DodgerBlue;\n"
"border-radius: 12px;\n"
"  color: white;\n"
"font: 75 7pt bold \"MS Shell Dlg 2\";\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: RoyalBlue;\n"
"}")
        self.pushButton_39.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_40 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_40.setGeometry(QtCore.QRect(240, 340, 71, 31))
        self.pushButton_40.setStyleSheet(" .QPushButton{\n"
"  background-color: DodgerBlue;\n"
"border-radius: 12px;\n"
"  color: white;\n"
"font: 75 7pt bold \"MS Shell Dlg 2\";\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: RoyalBlue;\n"
"}")
        self.pushButton_40.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_41 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_41.setGeometry(QtCore.QRect(240, 400, 71, 31))
        self.pushButton_41.setStyleSheet(" .QPushButton{\n"
"  background-color: DodgerBlue;\n"
"border-radius: 12px;\n"
"  color: white;\n"
"font: 75 7pt bold \"MS Shell Dlg 2\";\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: RoyalBlue;\n"
"}")
        self.pushButton_41.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_42 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_42.setGeometry(QtCore.QRect(240, 460, 71, 31))
        self.pushButton_42.setStyleSheet(" .QPushButton{\n"
"  background-color: DodgerBlue;\n"
"border-radius: 12px;\n"
"  color: white;\n"
"font: 75 7pt bold \"MS Shell Dlg 2\";\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: RoyalBlue;\n"
"}")
        self.pushButton_42.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_42.setObjectName("pushButton_42")
        self.pushButton_43 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_43.setGeometry(QtCore.QRect(240, 520, 71, 31))
        self.pushButton_43.setStyleSheet(" .QPushButton{\n"
"  background-color: DodgerBlue;\n"
"border-radius: 12px;\n"
"  color: white;\n"
"font: 75 7pt bold \"MS Shell Dlg 2\";\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: RoyalBlue;\n"
"}")
        self.pushButton_43.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_43.setObjectName("pushButton_43")
        self.pushButton_44 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_44.setGeometry(QtCore.QRect(240, 580, 71, 31))
        self.pushButton_44.setStyleSheet(" .QPushButton{\n"
"  background-color: DodgerBlue;\n"
"border-radius: 12px;\n"
"  color: white;\n"
"font: 75 7pt bold \"MS Shell Dlg 2\";\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: RoyalBlue;\n"
"}")
        self.pushButton_44.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_44.setObjectName("pushButton_44")
        self.pushButton_45 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_45.setGeometry(QtCore.QRect(240, 640, 71, 31))
        self.pushButton_45.setStyleSheet(" .QPushButton{\n"
"  background-color: DodgerBlue;\n"
"border-radius: 12px;\n"
"  color: white;\n"
"font: 75 7pt bold \"MS Shell Dlg 2\";\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: RoyalBlue;\n"
"}")
        self.pushButton_45.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_45.setObjectName("pushButton_45")
        self.pushButton_46 = QtWidgets.QPushButton(self.frame_16)
        self.pushButton_46.setGeometry(QtCore.QRect(240, 700, 71, 31))
        self.pushButton_46.setStyleSheet(" .QPushButton{\n"
"  background-color: DodgerBlue;\n"
"border-radius: 12px;\n"
"  color: white;\n"
"font: 75 7pt bold \"MS Shell Dlg 2\";\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: RoyalBlue;\n"
"}")
        self.pushButton_46.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_46.setObjectName("pushButton_46")
        self.verticalLayout_2.addWidget(self.frame_16)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_6.setText(_translate("MainWindow", "DashBoard"))
        self.pushButton_8.setText(_translate("MainWindow", "Employee"))
        self.pushButton_9.setText(_translate("MainWindow", "Projects"))
        self.pushButton_7.setText(_translate("MainWindow", "Payroll"))
        self.pushButton_5.setText(_translate("MainWindow", "Survielance"))
        self.pushButton_3.setText(_translate("MainWindow", "Tasks"))
        self.pushButton_4.setText(_translate("MainWindow", "Chat"))
        self.pushButton_2.setText(_translate("MainWindow", "Settings"))
        self.label_11.setText(_translate("MainWindow", "On Leave"))
        self.label_10.setText(_translate("MainWindow", "4"))
        self.label_13.setText(_translate("MainWindow", "10%"))
        self.label_12.setText(_translate("MainWindow", "22/09/2022"))
        self.label_7.setText(_translate("MainWindow", "On Board"))
        self.label_6.setText(_translate("MainWindow", "31"))
        self.label_9.setText(_translate("MainWindow", "86%"))
        self.label_8.setText(_translate("MainWindow", "22/9/2022"))
        self.label_15.setText(_translate("MainWindow", "Absent"))
        self.label_14.setText(_translate("MainWindow", "3"))
        self.label_17.setText(_translate("MainWindow", "4%"))
        self.label_16.setText(_translate("MainWindow", "22/09/2022"))
        self.label_2.setText(_translate("MainWindow", "Total"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">38</span></p></body></html>"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Search......."))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#ffffff;\">Project Deatils</span></p></body></html>"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">HRMS</span></p></body></html>"))
        self.label_35.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; color:#ffffff;\">Sep 12</span></p></body></html>"))
        self.toggleButton_7.setText(_translate("MainWindow", "18"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Team</span></p></body></html>"))
        self.pushButton_11.setText(_translate("MainWindow", "Leadres"))
        self.pushButton_12.setText(_translate("MainWindow", "Managers"))
        self.pushButton_13.setText(_translate("MainWindow", "EMPLOYEEs"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Search......."))
        self.label_21.setText(_translate("MainWindow", "Total"))
        self.label_22.setText(_translate("MainWindow", "On Board"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ffffff;\">14</span></p></body></html>"))
        self.label_23.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; color:#ffffff;\">18</span></p></body></html>"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Deadline</span></p></body></html>"))
        self.label_62.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; color:#ffffff;\">Sep 30</span></p></body></html>"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Progress</span></p></body></html>"))
        self.label_63.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; color:#ffffff;\">85%</span></p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Employees</span></p></body></html>"))
        self.pushButton_15.setText(_translate("MainWindow", "EMPLOYEE 101"))
        self.pushButton_16.setText(_translate("MainWindow", "EMPLOYEE 101"))
        self.pushButton_17.setText(_translate("MainWindow", "EMPLOYEE 101"))
        self.pushButton_18.setText(_translate("MainWindow", "EMPLOYEE 101"))
        self.pushButton_19.setText(_translate("MainWindow", "EMPLOYEE 101"))
        self.pushButton_20.setText(_translate("MainWindow", "EMPLOYEE 101"))
        self.pushButton_21.setText(_translate("MainWindow", "EMPLOYEE 101"))
        self.label_36.setText(_translate("MainWindow", "UI/uX"))
        self.label_37.setText(_translate("MainWindow", "UI/uX"))
        self.label_38.setText(_translate("MainWindow", "UI/uX"))
        self.label_64.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">DBA</p></body></html>"))
        self.label_65.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">BackEND</p></body></html>"))
        self.label_66.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">BackEND</p></body></html>"))
        self.label_67.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">BackEND</p></body></html>"))
        self.pushButton_22.setText(_translate("MainWindow", "EMPLOYEE 101"))
        self.pushButton_48.setText(_translate("MainWindow", "EMPLOYEE 101"))
        self.pushButton_49.setText(_translate("MainWindow", "EMPLOYEE 101"))
        self.comboBox.setItemText(0, _translate("MainWindow", "HRMS"))
        self.comboBox.setItemText(1, _translate("MainWindow", "ECOM"))
        self.label_28.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">sample Graph</span></p></body></html>"))
        self.label_32.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">TechTok4U@admin</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "ADD"))
        self.pushButton_23.setText(_translate("MainWindow", "Project Manager"))
        self.pushButton_24.setText(_translate("MainWindow", "EMPLOYEE 101"))
        self.pushButton_25.setText(_translate("MainWindow", "EMPLOYEE 102"))
        self.pushButton_26.setText(_translate("MainWindow", "EMPLOYEE 103"))
        self.pushButton_27.setText(_translate("MainWindow", "EMPLOYEE 104"))
        self.pushButton_28.setText(_translate("MainWindow", "EMPLOYEE 105"))
        self.pushButton_29.setText(_translate("MainWindow", "EMPLOYEE 106"))
        self.pushButton_30.setText(_translate("MainWindow", "EMPLOYEE 107"))
        self.pushButton_31.setText(_translate("MainWindow", "EMPLOYEE 108"))
        self.pushButton_32.setText(_translate("MainWindow", "EMPLOYEE 101"))
        self.pushButton_33.setText(_translate("MainWindow", "EMPLOYEE 101"))
        self.pushButton_34.setText(_translate("MainWindow", "EMPLOYEE 101"))
        self.pushButton_35.setText(_translate("MainWindow", "REMOVE"))
        self.pushButton_36.setText(_translate("MainWindow", "REMOVE"))
        self.pushButton_37.setText(_translate("MainWindow", "REMOVE"))
        self.pushButton_38.setText(_translate("MainWindow", "REMOVE"))
        self.pushButton_39.setText(_translate("MainWindow", "REMOVE"))
        self.pushButton_40.setText(_translate("MainWindow", "REMOVE"))
        self.pushButton_41.setText(_translate("MainWindow", "REMOVE"))
        self.pushButton_42.setText(_translate("MainWindow", "REMOVE"))
        self.pushButton_43.setText(_translate("MainWindow", "REMOVE"))
        self.pushButton_44.setText(_translate("MainWindow", "REMOVE"))
        self.pushButton_45.setText(_translate("MainWindow", "REMOVE"))
        self.pushButton_46.setText(_translate("MainWindow", "REMOVE"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
