# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prjdetails.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(960, 459)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-10, -10, 971, 471))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.frame.setStyleSheet("background-color:#262626;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_45 = QtWidgets.QFrame(self.frame)
        self.frame_45.setGeometry(QtCore.QRect(20, 20, 281, 441))
        self.frame_45.setStyleSheet("border-radius: 15px;\n"
" background-color: #000000;")
        self.frame_45.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.label_19 = QtWidgets.QLabel(self.frame_45)
        self.label_19.setGeometry(QtCore.QRect(80, 20, 81, 23))
        self.label_19.setStyleSheet("border:none;")
        self.label_19.setObjectName("label_19")
        self.label_35 = QtWidgets.QLabel(self.frame_45)
        self.label_35.setGeometry(QtCore.QRect(170, 20, 61, 20))
        self.label_35.setMinimumSize(QtCore.QSize(0, 20))
        self.label_35.setMaximumSize(QtCore.QSize(70, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("color: rgb(203, 203, 203);\n"
"background-color: rgb(255, 17, 80);\n"
"padding: 1px;\n"
"border-radius: 8px;")
        self.label_35.setObjectName("label_35")
        self.label = QtWidgets.QLabel(self.frame_45)
        self.label.setGeometry(QtCore.QRect(10, 10, 71, 61))
        self.label.setStyleSheet("border:none;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../employee/minilogo.png"))
        self.label.setObjectName("label")
        self.frame_46 = QtWidgets.QFrame(self.frame_45)
        self.frame_46.setGeometry(QtCore.QRect(0, 120, 271, 141))
        self.frame_46.setStyleSheet("border: 1px solid rgb(34, 24, 97);\n"
" background-color: #000000;\n"
"border:none;")
        self.frame_46.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.frame_13 = QtWidgets.QFrame(self.frame_46)
        self.frame_13.setGeometry(QtCore.QRect(-10, 80, 301, 61))
        self.frame_13.setStyleSheet(".QFrame{\n"
"background-color:#000000;\n"
"}\n"
"\n"
".QFrame:hover {\n"
"  background-color: #52527a;\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_25 = QtWidgets.QLabel(self.frame_13)
        self.label_25.setGeometry(QtCore.QRect(20, 0, 81, 23))
        self.label_25.setStyleSheet("background-color:none;")
        self.label_25.setObjectName("label_25")
        self.progressBar_5 = QtWidgets.QProgressBar(self.frame_13)
        self.progressBar_5.setGeometry(QtCore.QRect(20, 40, 241, 16))
        self.progressBar_5.setMinimumSize(QtCore.QSize(0, 16))
        self.progressBar_5.setMaximumSize(QtCore.QSize(16777215, 16))
        self.progressBar_5.setStyleSheet("QProgressBar {\n"
"    color: rgb(177, 177, 177);\n"
"    border: none;\n"
"    background-color: rgb(102, 102, 102);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #ff0000;\n"
"    border-radius : 8px;\n"
"}     ")
        self.progressBar_5.setProperty("value", 79)
        self.progressBar_5.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_5.setTextVisible(False)
        self.progressBar_5.setObjectName("progressBar_5")
        self.label_62 = QtWidgets.QLabel(self.frame_13)
        self.label_62.setGeometry(QtCore.QRect(120, 10, 61, 20))
        self.label_62.setMinimumSize(QtCore.QSize(0, 20))
        self.label_62.setMaximumSize(QtCore.QSize(70, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setStyleSheet("color: rgb(203, 203, 203);\n"
"background-color: rgb(255, 17, 80);\n"
"padding: 1px;\n"
"border-radius: 8px;")
        self.label_62.setObjectName("label_62")
        self.label_26 = QtWidgets.QLabel(self.frame_46)
        self.label_26.setGeometry(QtCore.QRect(10, 20, 81, 23))
        self.label_26.setObjectName("label_26")
        self.label_63 = QtWidgets.QLabel(self.frame_46)
        self.label_63.setGeometry(QtCore.QRect(130, 20, 47, 20))
        self.label_63.setMinimumSize(QtCore.QSize(0, 20))
        self.label_63.setMaximumSize(QtCore.QSize(70, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setStyleSheet("color:#ffffff;\n"
"background-color: rgb(255, 17, 80);\n"
"padding: 1px;\n"
"border-radius: 8px;")
        self.label_63.setObjectName("label_63")
        self.progressBar_4 = QtWidgets.QProgressBar(self.frame_46)
        self.progressBar_4.setGeometry(QtCore.QRect(10, 50, 241, 16))
        self.progressBar_4.setMinimumSize(QtCore.QSize(0, 16))
        self.progressBar_4.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.progressBar_4.setFont(font)
        self.progressBar_4.setAutoFillBackground(False)
        self.progressBar_4.setStyleSheet("QProgressBar {\n"
"    color: rgb(177, 177, 177);\n"
"    border: none;\n"
"    background-color: rgb(102, 102, 102);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: rgb(7, 255, 119);\n"
"    border-radius : 8px;\n"
"}     ")
        self.progressBar_4.setProperty("value", 75)
        self.progressBar_4.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_4.setTextVisible(False)
        self.progressBar_4.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_4.setInvertedAppearance(False)
        self.progressBar_4.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBar_4.setObjectName("progressBar_4")
        self.frame_47 = QtWidgets.QFrame(self.frame_45)
        self.frame_47.setGeometry(QtCore.QRect(0, 270, 281, 161))
        self.frame_47.setStyleSheet("border:none;\n"
" background-color: #ccffcc;")
        self.frame_47.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_47.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_47.setObjectName("frame_47")
        self.label_21 = QtWidgets.QLabel(self.frame_47)
        self.label_21.setGeometry(QtCore.QRect(30, 70, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("QLabel {\n"
"    color: rgb(152, 152, 152);\n"
"    border: none;\n"
"}")
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.frame_5 = QtWidgets.QFrame(self.frame_47)
        self.frame_5.setGeometry(QtCore.QRect(110, 40, 171, 111))
        self.frame_5.setStyleSheet("background-color:#000000;")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_22 = QtWidgets.QLabel(self.frame_5)
        self.label_22.setGeometry(QtCore.QRect(50, 30, 69, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("QLabel {\n"
"    color: rgb(152, 152, 152);\n"
"    border: none;\n"
"}")
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_24 = QtWidgets.QLabel(self.frame_5)
        self.label_24.setGeometry(QtCore.QRect(50, 70, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("QLabel {\n"
"    color: rgb(199, 199, 199);\n"
"    border: none;\n"
"}")
        self.label_24.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_24.setObjectName("label_24")
        self.label_23 = QtWidgets.QLabel(self.frame_47)
        self.label_23.setGeometry(QtCore.QRect(20, 100, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("\n"
"    color: #000000;\n"
"")
        self.label_23.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_23.setObjectName("label_23")
        self.pushButton_10 = QtWidgets.QPushButton(self.frame_47)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 10, 36, 36))
        self.pushButton_10.setMinimumSize(QtCore.QSize(36, 36))
        self.pushButton_10.setMaximumSize(QtCore.QSize(36, 36))
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgb(13, 9, 36);\n"
"    border-radius: 18;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 0, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.pushButton_10.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../Downloads/25-254406_white-person-icon-png-people-white-icon-png (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon)
        self.pushButton_10.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_10.setObjectName("pushButton_10")
        self.label_20 = QtWidgets.QLabel(self.frame_47)
        self.label_20.setGeometry(QtCore.QRect(50, 10, 61, 31))
        self.label_20.setStyleSheet("")
        self.label_20.setObjectName("label_20")
        self.toggleButton_7 = QtWidgets.QPushButton(self.frame_45)
        self.toggleButton_7.setGeometry(QtCore.QRect(70, 50, 90, 26))
        self.toggleButton_7.setMinimumSize(QtCore.QSize(90, 26))
        self.toggleButton_7.setMaximumSize(QtCore.QSize(90, 26))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.toggleButton_7.setFont(font)
        self.toggleButton_7.setStyleSheet("QPushButton {\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    background-color: rgb(30, 30, 30);\n"
"    border-left: 3px solid rgb(30, 30, 30);\n"
"    border-right: 3px solid rgb(30, 30, 30);\n"
"    color:#ffffff;\n"
"    border-radius: 13px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-left: 3px solid rgb(255, 85, 0);\n"
"    border-right: 3px solid rgb(255, 85, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(25, 25, 25);\n"
"}")
        self.toggleButton_7.setIcon(icon)
        self.toggleButton_7.setObjectName("toggleButton_7")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(310, 20, 651, 441))
        self.frame_3.setStyleSheet("background-color:#000000;\n"
"border-radius: 25px;")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.toggleButton_8 = QtWidgets.QPushButton(self.frame_3)
        self.toggleButton_8.setGeometry(QtCore.QRect(180, 30, 90, 26))
        self.toggleButton_8.setMinimumSize(QtCore.QSize(90, 26))
        self.toggleButton_8.setMaximumSize(QtCore.QSize(90, 26))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.toggleButton_8.setFont(font)
        self.toggleButton_8.setStyleSheet("QPushButton {\n"
"    font: 75 10pt \"MS Shell Dlg 2\";\n"
"    font: 75 8pt \"MS Shell Dlg 2\";\n"
"    border: none;\n"
"    background-color: rgb(30, 30, 30);\n"
"    border-left: 3px solid rgb(30, 30, 30);\n"
"    border-right: 3px solid rgb(30, 30, 30);\n"
"    color:#ffffff;\n"
"    border-radius: 13px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-left: 3px solid rgb(255, 85, 0);\n"
"    border-right: 3px solid rgb(255, 85, 0);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(25, 25, 25);\n"
"}")
        self.toggleButton_8.setIcon(icon)
        self.toggleButton_8.setObjectName("toggleButton_8")
        self.pushButton_11 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 10, 36, 36))
        self.pushButton_11.setMinimumSize(QtCore.QSize(36, 36))
        self.pushButton_11.setMaximumSize(QtCore.QSize(36, 36))
        self.pushButton_11.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: rgb(13, 9, 36);\n"
"    border-radius: 18;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 0, 255);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 0, 0);\n"
"}")
        self.pushButton_11.setText("")
        self.pushButton_11.setIcon(icon)
        self.pushButton_11.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_11.setObjectName("pushButton_11")
        self.label_27 = QtWidgets.QLabel(self.frame_3)
        self.label_27.setGeometry(QtCore.QRect(60, 10, 61, 41))
        self.label_27.setStyleSheet("")
        self.label_27.setObjectName("label_27")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setGeometry(QtCore.QRect(20, 100, 261, 331))
        self.frame_2.setStyleSheet("background-color:#000000;\n"
"border:none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_12.setGeometry(QtCore.QRect(0, 0, 261, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setStyleSheet("\n"
".QPushButton:hover {\n"
"  background-color: #003366;\n"
"}\n"
"\n"
".QPushButton{\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../Downloads/png-transparent-businessperson-computer-icons-avatar-avatar-heroes-public-relations-business (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon1)
        self.pushButton_12.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_13.setGeometry(QtCore.QRect(0, 50, 261, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        self.pushButton_13.setStyleSheet("\n"
".QPushButton:hover {\n"
"  background-color:#003366;\n"
"}\n"
"\n"
".QPushButton{\n"
"background-color:#000000;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"}")
        self.pushButton_13.setIcon(icon1)
        self.pushButton_13.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_14.setGeometry(QtCore.QRect(0, 100, 261, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setStyleSheet("\n"
".QPushButton:hover {\n"
"  background-color: #003366;\n"
"}\n"
"\n"
".QPushButton{\n"
"background-color:#000000;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"  border:none;\n"
"}")
        self.pushButton_14.setIcon(icon1)
        self.pushButton_14.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_14.setObjectName("pushButton_14")
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setGeometry(QtCore.QRect(20, 60, 250, 41))
        self.frame_7.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_7.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_7.setStyleSheet("background-color: rgb(13, 9, 36);")
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 10, 201, 31))
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_2.setStyleSheet("background-color:#000000;\n"
"border: 1px  solid #ccc;  \n"
"border-radius: 15px;\n"
"color:#ffffff;\n"
"font: 75 12pt \"MS Shell Dlg 2\";\n"
"font-color:#ffffff;\n"
"input[type=text] {\n"
"    border: 1px solid #ffffff;  \n"
"  }")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(self.frame_7)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../../../Downloads/search-3-xxl (1) (1).png"))
        self.label_5.setObjectName("label_5")
        self.scrollArea = QtWidgets.QScrollArea(self.frame_3)
        self.scrollArea.setGeometry(QtCore.QRect(280, 100, 353, 331))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setStyleSheet(" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(56, 56, 85);\n"
" }\n"
" QScrollArea{\n"
"border:none;\n"
"}")
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -106, 1218, 1218))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame_4.setMinimumSize(QtCore.QSize(1200, 1200))
        self.frame_4.setStyleSheet("background-color:black;\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.pushButton = QtWidgets.QPushButton(self.frame_4)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 81, 31))
        self.pushButton.setStyleSheet("border-radius: 12px;\n"
"text-align: center;\n"
"color:#ffffff;\n"
"background-color:#cc33ff;")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../../../Downloads/67-679828_white-plus-png-plus-icon-white-png-transparent (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_2.setGeometry(QtCore.QRect(0, 30, 331, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"\n"
"")
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_7.setGeometry(QtCore.QRect(0, 90, 331, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"")
        self.pushButton_7.setIcon(icon1)
        self.pushButton_7.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_8.setGeometry(QtCore.QRect(0, 150, 331, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"")
        self.pushButton_8.setIcon(icon1)
        self.pushButton_8.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_9.setGeometry(QtCore.QRect(0, 210, 331, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"")
        self.pushButton_9.setIcon(icon1)
        self.pushButton_9.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_15 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_15.setGeometry(QtCore.QRect(0, 270, 331, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"")
        self.pushButton_15.setIcon(icon1)
        self.pushButton_15.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_16.setGeometry(QtCore.QRect(0, 330, 331, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        self.pushButton_16.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"")
        self.pushButton_16.setIcon(icon1)
        self.pushButton_16.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_17.setGeometry(QtCore.QRect(0, 390, 331, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"")
        self.pushButton_17.setIcon(icon1)
        self.pushButton_17.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_18.setGeometry(QtCore.QRect(0, 450, 331, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_18.sizePolicy().hasHeightForWidth())
        self.pushButton_18.setSizePolicy(sizePolicy)
        self.pushButton_18.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"")
        self.pushButton_18.setIcon(icon1)
        self.pushButton_18.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_19.setGeometry(QtCore.QRect(0, 510, 331, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_19.sizePolicy().hasHeightForWidth())
        self.pushButton_19.setSizePolicy(sizePolicy)
        self.pushButton_19.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"")
        self.pushButton_19.setIcon(icon1)
        self.pushButton_19.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_20.setGeometry(QtCore.QRect(0, 570, 331, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_20.sizePolicy().hasHeightForWidth())
        self.pushButton_20.setSizePolicy(sizePolicy)
        self.pushButton_20.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"")
        self.pushButton_20.setIcon(icon1)
        self.pushButton_20.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_21.setGeometry(QtCore.QRect(0, 630, 331, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_21.sizePolicy().hasHeightForWidth())
        self.pushButton_21.setSizePolicy(sizePolicy)
        self.pushButton_21.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"")
        self.pushButton_21.setIcon(icon1)
        self.pushButton_21.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_22.setGeometry(QtCore.QRect(0, 690, 331, 61))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_22.sizePolicy().hasHeightForWidth())
        self.pushButton_22.setSizePolicy(sizePolicy)
        self.pushButton_22.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color:#ffffff;\n"
"text-align:left;\n"
"")
        self.pushButton_22.setIcon(icon1)
        self.pushButton_22.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 40, 71, 31))
        self.pushButton_3.setStyleSheet(" .QPushButton{\n"
"  background-color: DodgerBlue;\n"
"border-radius: 12px;\n"
"  color: white;\n"
"font: 75 7pt bold \"MS Shell Dlg 2\";\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: RoyalBlue;\n"
"}")
        self.pushButton_3.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_23 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_23.setGeometry(QtCore.QRect(240, 100, 71, 31))
        self.pushButton_23.setStyleSheet(" .QPushButton{\n"
"  background-color: DodgerBlue;\n"
"border-radius: 12px;\n"
"  color: white;\n"
"font: 75 7pt bold \"MS Shell Dlg 2\";\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: RoyalBlue;\n"
"}")
        self.pushButton_23.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_24.setGeometry(QtCore.QRect(240, 160, 71, 31))
        self.pushButton_24.setStyleSheet(" .QPushButton{\n"
"  background-color: DodgerBlue;\n"
"border-radius: 12px;\n"
"  color: white;\n"
"font: 75 7pt bold \"MS Shell Dlg 2\";\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: RoyalBlue;\n"
"}")
        self.pushButton_24.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_25.setGeometry(QtCore.QRect(240, 220, 71, 31))
        self.pushButton_25.setStyleSheet(" .QPushButton{\n"
"  background-color: DodgerBlue;\n"
"border-radius: 12px;\n"
"  color: white;\n"
"font: 75 7pt bold \"MS Shell Dlg 2\";\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: RoyalBlue;\n"
"}")
        self.pushButton_25.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_26.setGeometry(QtCore.QRect(240, 280, 71, 31))
        self.pushButton_26.setStyleSheet(" .QPushButton{\n"
"  background-color: DodgerBlue;\n"
"border-radius: 12px;\n"
"  color: white;\n"
"font: 75 7pt bold \"MS Shell Dlg 2\";\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: RoyalBlue;\n"
"}")
        self.pushButton_26.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_27.setGeometry(QtCore.QRect(240, 340, 71, 31))
        self.pushButton_27.setStyleSheet(" .QPushButton{\n"
"  background-color: DodgerBlue;\n"
"border-radius: 12px;\n"
"  color: white;\n"
"font: 75 7pt bold \"MS Shell Dlg 2\";\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: RoyalBlue;\n"
"}")
        self.pushButton_27.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_28.setGeometry(QtCore.QRect(240, 400, 71, 31))
        self.pushButton_28.setStyleSheet(" .QPushButton{\n"
"  background-color: DodgerBlue;\n"
"border-radius: 12px;\n"
"  color: white;\n"
"font: 75 7pt bold \"MS Shell Dlg 2\";\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: RoyalBlue;\n"
"}")
        self.pushButton_28.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_29.setGeometry(QtCore.QRect(240, 460, 71, 31))
        self.pushButton_29.setStyleSheet(" .QPushButton{\n"
"  background-color: DodgerBlue;\n"
"border-radius: 12px;\n"
"  color: white;\n"
"font: 75 7pt bold \"MS Shell Dlg 2\";\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: RoyalBlue;\n"
"}")
        self.pushButton_29.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_30.setGeometry(QtCore.QRect(240, 520, 71, 31))
        self.pushButton_30.setStyleSheet(" .QPushButton{\n"
"  background-color: DodgerBlue;\n"
"border-radius: 12px;\n"
"  color: white;\n"
"font: 75 7pt bold \"MS Shell Dlg 2\";\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: RoyalBlue;\n"
"}")
        self.pushButton_30.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_31.setGeometry(QtCore.QRect(240, 580, 71, 31))
        self.pushButton_31.setStyleSheet(" .QPushButton{\n"
"  background-color: DodgerBlue;\n"
"border-radius: 12px;\n"
"  color: white;\n"
"font: 75 7pt bold \"MS Shell Dlg 2\";\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: RoyalBlue;\n"
"}")
        self.pushButton_31.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_32.setGeometry(QtCore.QRect(240, 640, 71, 31))
        self.pushButton_32.setStyleSheet(" .QPushButton{\n"
"  background-color: DodgerBlue;\n"
"border-radius: 12px;\n"
"  color: white;\n"
"font: 75 7pt bold \"MS Shell Dlg 2\";\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: RoyalBlue;\n"
"}")
        self.pushButton_32.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_33 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_33.setGeometry(QtCore.QRect(240, 700, 71, 31))
        self.pushButton_33.setStyleSheet(" .QPushButton{\n"
"  background-color: DodgerBlue;\n"
"border-radius: 12px;\n"
"  color: white;\n"
"font: 75 7pt bold \"MS Shell Dlg 2\";\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: RoyalBlue;\n"
"}")
        self.pushButton_33.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_33.setObjectName("pushButton_33")
        self.horizontalLayout_2.addWidget(self.frame_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setGeometry(QtCore.QRect(430, 60, 191, 31))
        self.pushButton_4.setStyleSheet(" .QPushButton{\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"  background-color: DodgerBlue;\n"
"border-radius: 12px;\n"
"  color: white;\n"
"\n"
"  cursor: pointer;\n"
"}\n"
"\n"
".QPushButton:hover {\n"
"  background-color: RoyalBlue;\n"
"}")
        self.pushButton_4.setIconSize(QtCore.QSize(25, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.frame)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_19.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">HRMS</span></p></body></html>"))
        self.label_35.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; color:#ffffff;\">Sep 12</span></p></body></html>"))
        self.label_25.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Deadline</span></p></body></html>"))
        self.label_62.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:9pt; color:#ffffff;\">Sep 30</span></p></body></html>"))
        self.label_26.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ffffff;\">Progress</span></p></body></html>"))
        self.label_63.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; color:#ffffff;\">85%</span></p></body></html>"))
        self.label_21.setText(_translate("Form", "<html><head/><body><p align=\"center\">Total</p></body></html>"))
        self.label_22.setText(_translate("Form", "On Board"))
        self.label_24.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ffffff;\">14</span></p></body></html>"))
        self.label_23.setText(_translate("Form", "<html><head/><body><p>18</p></body></html>"))
        self.label_20.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600; color:#000000;\">Team</span></p></body></html>"))
        self.toggleButton_7.setText(_translate("Form", "18"))
        self.toggleButton_8.setText(_translate("Form", "18"))
        self.label_27.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600; color:#ffffff;\">Team</span></p></body></html>"))
        self.pushButton_12.setText(_translate("Form", "Leadres"))
        self.pushButton_13.setText(_translate("Form", "Managers"))
        self.pushButton_14.setText(_translate("Form", "EMPLOYEEs"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Search......."))
        self.pushButton.setText(_translate("Form", "ADD"))
        self.pushButton_2.setText(_translate("Form", "Project Manager"))
        self.pushButton_7.setText(_translate("Form", "EMPLOYEE 101"))
        self.pushButton_8.setText(_translate("Form", "EMPLOYEE 102"))
        self.pushButton_9.setText(_translate("Form", "EMPLOYEE 103"))
        self.pushButton_15.setText(_translate("Form", "EMPLOYEE 104"))
        self.pushButton_16.setText(_translate("Form", "EMPLOYEE 105"))
        self.pushButton_17.setText(_translate("Form", "EMPLOYEE 106"))
        self.pushButton_18.setText(_translate("Form", "EMPLOYEE 107"))
        self.pushButton_19.setText(_translate("Form", "EMPLOYEE 108"))
        self.pushButton_20.setText(_translate("Form", "EMPLOYEE 101"))
        self.pushButton_21.setText(_translate("Form", "EMPLOYEE 101"))
        self.pushButton_22.setText(_translate("Form", "EMPLOYEE 101"))
        self.pushButton_3.setText(_translate("Form", "REMOVE"))
        self.pushButton_23.setText(_translate("Form", "REMOVE"))
        self.pushButton_24.setText(_translate("Form", "REMOVE"))
        self.pushButton_25.setText(_translate("Form", "REMOVE"))
        self.pushButton_26.setText(_translate("Form", "REMOVE"))
        self.pushButton_27.setText(_translate("Form", "REMOVE"))
        self.pushButton_28.setText(_translate("Form", "REMOVE"))
        self.pushButton_29.setText(_translate("Form", "REMOVE"))
        self.pushButton_30.setText(_translate("Form", "REMOVE"))
        self.pushButton_31.setText(_translate("Form", "REMOVE"))
        self.pushButton_32.setText(_translate("Form", "REMOVE"))
        self.pushButton_33.setText(_translate("Form", "REMOVE"))
        self.pushButton_4.setText(_translate("Form", "Manage Tasks"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
